### ISSUE TITLE
Feedback Quiz Lv.4

### ISSUE THREAD

**Issue by udiiin** [filbertreinaldha/sandboxhsi-nextjs-level4-blog#1]
Halo Mas @filbertreinaldha, terima kasih utk submissionnya.  
Saya ada beberapa feedback:

**1.)**  
File `dist/*.js` tidak diperlukan, bisa dihapus saja

**2.)**  
Typing-nya saat menggunakan axios bisa diimprove seperti ini, sesuai dengan tipe responsenya.

<img width="727" alt="Screen Shot 2023-07-08 at 10 12 09" src="https://github.com/filbertreinaldha/sandboxhsi-nextjs-level4-blog/assets/129339659/c3354285-7642-4d17-9058-64c3fb2d4afc">

**3.)**  
Component `PostList`, property `initialArticles: any` sebaiknya diubah menjadi `initialArticles: TArticleList`.  
Begitu juga dengan component2 lain (`PostDetail`, `RelatedPost`, dll..) yang typenya masih `any`, bisa diimprove lagi.

**4.)**  
Karena saat fetch itu menggunakan `{ params: params }`, akhirnya akan jadi error ketika buka URL https://sandboxhsi-nextjs-level4-blog.vercel.app/?cek=1  
Di situ param `?cek=1` akan menyebabkan error.  
Sebaiknya dibuat hanya param yg valid yg dikirim saat fetch data.

**5.)**  
Pada saat menjalankan build, halaman detail artikel yg digenerate scr SSG itu hanya 4 artikel, karena fungsi `generateStaticParams` hanya me-return 4 item.

.

Semoga dimudahkan, barokallaahu fiik...

**Comment by filbertreinaldha** [comment]
Halo Mas @udiiin syukron untuk feedback-nya. sudah ana push update-nya ya. berikut beberapa poin update-nya:
1. dist folder sudah dihapus. Sebelumnya sepertinya sudah saya hapus, tapi kayaknya ke-generate lagi pas test build terakhir sebelum ini.
2. insyaaAllah sebagian besar type any sudah saya ganti ke yang sesuai, kecuali beberapa yang ada hubungannya sama QueryKey di hook useInfiniteQuery. Selalu nggak pas saya juga bingung. Akhirnya tetep saya pakein any.
3. Sama dengan poin ke-2, sudah diganti juga ke type yang sesuai.
4. Parameter dari query string sudah divalidate, hanya terima "new", "popular", atau kosong. Selain itu saya larikan ke notFound.
5. List slug sudah saya update sehingga ke-12 judul blog sudah di-generate untuk static page.

Mohon masukannya lagi ya mas, terutama mungkin poin nomer 2 yang terkait hook useInfiniteQuery, mungkin mas Afif ada pengalaman...

**Comment by afiiif** [comment]
Saya ada feedback lagi Mas @filbertreinaldha:

**1.)**  
Terkait penggunaan _async-await_ vs _promise-chain_.  
Pada code ini, variable `response` itu di-await, sehingga apa yg ada di block `catch` juga di-return.  
Akhirnya type ketika kondisi tidak error & ketika kondisi error akan tercampur, jadinya tipe `response` = `any`.
<img width="450" alt="Screen Shot 2023-07-13 at 03 31 05" src="https://github.com/filbertreinaldha/sandboxhsi-nextjs-level4-blog/assets/43276538/e1f913f3-46da-4f29-8b9b-b1112bc1514d">

Sebaiknya jangan di-catch dan di-return valuenya menjadi `response`, tetapi bisa seperti ini biar type nya lebih jelas:
<img width="295" alt="Screen Shot 2023-07-13 at 03 37 15" src="https://github.com/filbertreinaldha/sandboxhsi-nextjs-level4-blog/assets/43276538/b4b9d40c-7847-4b16-b539-2b0bf720f0bc">

**2.)**  
> _Parameter dari query string sudah divalidate, hanya terima "new", "popular", atau kosong. Selain itu saya larikan ke notFound._

Sebaiknya jangan mas..  
Umumnya, query parameter yg tidak sesuai itu diabaikan saja.  
Contoh: halaman ini bisa tetap kita buka tanpa error,  
👉 https://github.com/?tes=123  
👉 https://www.google.com/?tes=123

Jadi better spt ini:  
Apabila `/?sort=popular` maka tampilkan dg urutan popular,  
Selain itu, tampilkan dg urutan new,  
Abaikan query parameter lainnya.

**Comment by udiiin** [comment]
Saya ada feedback lagi Mas @filbertreinaldha:

**1.)**  
Terkait penggunaan _async-await_ vs _promise-chain_.  
Pada code ini, variable `response` itu di-await, sehingga apa yg ada di block `catch` juga di-return.  
Akhirnya type ketika kondisi tidak error & ketika kondisi error akan tercampur, jadinya tipe `response` = `any`.
<img width="490" alt="Screen Shot 2023-07-13 at 03 31 05" src="https://github.com/filbertreinaldha/sandboxhsi-nextjs-level4-blog/assets/43276538/e1f913f3-46da-4f29-8b9b-b1112bc1514d">

Sebaiknya jangan di-catch dan di-return valuenya menjadi `response`, tetapi bisa seperti ini biar type nya lebih jelas:
<img width="325" alt="Screen Shot 2023-07-13 at 03 37 15" src="https://github.com/filbertreinaldha/sandboxhsi-nextjs-level4-blog/assets/43276538/b4b9d40c-7847-4b16-b539-2b0bf720f0bc">

**2.)**  
> _Parameter dari query string sudah divalidate, hanya terima "new", "popular", atau kosong. Selain itu saya larikan ke notFound._

Sebaiknya jangan mas..  
Umumnya, query parameter yg tidak sesuai itu diabaikan saja.  
Contoh: halaman ini bisa tetap kita buka tanpa error,  
👉 https://github.com/?tes=123  
👉 https://www.google.com/?tes=123

Jadi better spt ini:  
Apabila `/?sort=popular` maka tampilkan dg urutan popular,  
Selain itu, tampilkan dg urutan new,  
Abaikan query parameter lainnya.

**Comment by filbertreinaldha** [comment]
1. Wah iya mas, bener juga. updated di latest push ya mas
2. Oke, updated juga di latest push.

Mohon direview lagi ya mas...

**Comment by udiiin** [comment]
Pastikan param yg dikirim saat get articles itu sesuai dengan dokumentasi API aja mas...

Utk poin ini:

> Apabila /?sort=popular maka tampilkan dg urutan popular,  
> Selain itu, tampilkan dg urutan new,  
> Abaikan query parameter lainnya.

Ketika user visit page dengan parameter ini: `/?sort=popular&a=1&b=2`, maka yg dikirim ke BE hanya `sort` saja, sisanya bisa diabaikan.

Saya tes buka https://sandboxhsi-nextjs-level4-blog.vercel.app/?sort=popular&a=1&b=2  
akan error saat load more.

**Comment by filbertreinaldha** [comment]
Ah iya, afwan mas, lupa ana update untuk client fetch-nya, kemarin benerin yang server fetch aja. updated ya mas.

**Comment by udiiin** [comment]
Sipp mas, mantaaab 👍 

Udah oke ✅  
Barokallaahu fiik...
